# Generated by Django 3.2 on 2021-06-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210526_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincycle',
            name='auto_click_power',
            field=models.IntegerField(default=0),
        ),
    ]
