# Generated by Django 3.2 on 2021-06-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_maincycle_auto_click_power'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boost',
            old_name='mainCycle',
            new_name='main_cycle',
        ),
    ]
